name: sketch2house3d
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - torchaudio>=2.0.0
  - numpy>=1.24.0
  - scipy>=1.11.0
  - scikit-learn>=1.3.0
  - scikit-image>=0.21.0
  - opencv>=4.8.0
  - pillow>=10.0.0
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - pandas>=2.0.0
  - pyyaml>=6.0.0
  - tqdm>=4.66.0
  - pytest>=7.4.0
  - black>=23.0.0
  - isort>=5.12.0
  - flake8>=6.0.0
  - pre-commit>=3.4.0
  - pip:
    - segmentation-models-pytorch>=0.3.0
    - albumentations>=1.3.0
    - open3d>=0.17.0
    - trimesh>=3.23.0
    - pyvista>=0.42.0
    - meshio>=5.3.0
    - pygltflib>=1.15.0
    - bpy>=3.6.0
    - fastapi>=0.104.0
    - uvicorn[standard]>=0.24.0
    - python-multipart>=0.0.6
    - jinja2>=3.1.0
    - pydantic>=2.4.0
    - jsonschema>=4.19.0
    - plotly>=5.17.0
    - wandb>=0.15.0
    - pytest-cov>=4.1.0
    - pytest-mock>=3.11.0
